#!/usr/bin/env bash

CWD=${PWD}
BIN="implant"
BINDIR="bin"
FLAGS="-d:release -d:ssl -d:nimOldCaseObjects"

# Check for dependencies
nimble install dotenv telebot

clear
# Build the binary
# Build for Linux
echo "[*] Compiling for Linux..."
nim c ${FLAGS} --hints:off --out:${BINDIR}/${BIN} ${BIN}.nim

# Build for Windows
# echo -e "\n[*] Compiling for Windows..."
# nim c ${FLAGS} -d:mingw --hints:off --out:${BINDIR}/${BIN}-windows.exe ${BIN}.nim

echo "[*] Finished compiling!"
echo "[*] Built binaries can be found at ${CWD}/${BINDIR}"

./bin/implant
